### ISSUE TITLE
Should emulator log level be debug?

### ISSUE THREAD

**Issue by FCO** [Humanstate/api-client-public-module#1]
I’ve cloned the repo, installed its dependencies on carton (carton) and ran the tests on it too (carton exec prove -l t). All the tests passed. But It seems the emulator log level is set to trace. Maybe it would be better to set to debug?

**Comment by yangakandeni** [comment]
It seems like the log level is set by 3rd party dependency modules .
i.e. `local/lib/perl5/Mojolicious.pm`, `local/lib/perl5/Mojolicious/Controller.pm` and `local/lib/perl5/Mojolicious/Routes.pm`

**Comment by FCO** [comment]
Yes, but that would be good to change that on emulator to avoid all those logs on testing, no?

**Comment by yangakandeni** [comment]
I agree. Thanks @FCO 🙇
